- import_tracker/import_tracker.py
- test/helpers.py
- test/sample_libs/env_import/__init__.py
- test/test_import_tracker.py
This PR passes all `os.environ` variables through to the `subprocess` in `TRACKING` mode. Some libraries require certain env-based config at import time, so without this those libraries may break or follow different paths when imported in the `subprocess`.
> PassThroughEnv: Pass the full env through in TRACKING mode

- import_tracker/__init__.py
- import_tracker/import_tracker.py
- test/test_import_tracker.py
Add `get_tracked_imports` to return the set of tracked imports for a given library
> GetTrackedImports: Add get_tracked_modules with tests

- import_tracker/__init__.py
Include `LazyModule` in the set of attributes exposed at the top level. It is useful as a standalone construct should be public.
> EvenLazierErrors: Expose LazyModule in the public API

- import_tracker/import_tracker.py
- test/test_import_tracker.py
In `get_required_packages` we want all imports represented, so we assume that if a package name can't be found, the import name itself is the package.
> Pass through unknown imports as packages

- import_tracker/lazy_import_errors.py
- requirements_test.txt
- scripts/run_tests.sh
- test/test_lazy_import_errors.py
The goal of `lazy_import_errors` is to allow modules within a library to be imported cleanly, even if they have missing imports, and then defer those imports until their contents are used. One of the most common uses of a module, however, is to use an attribute from it _at import time_. This typically looks like inheriting from a class within that module, or accessing a constant, or something similar. With the previous implementation where the `ModuleNotFoundError` is raised on `__getattr__` for the missing module placeholder, these import-time usecases would raise at import time for the enclosing library.
This PR further defers missing module errors until the last possible moment: usage of attributes from within the missing module. It does so by introducing the `_LazyAttrError` object …
> Even lazier errors

- import_tracker/__init__.py
- import_tracker/import_tracker.py
- import_tracker/setup_tools.py
- test/helpers.py
- test/test_import_tracker.py
- test/test_setup_tools.py
This package adds a sub-module `import_tracker.setup_tools`. This package currently only contains `parse_requirements` which encapsulates common logic for producing the `requirements` and `extras_requires` arguments to `setuptools.setup`.
> Setup tools

- import_tracker/__main__.py
- import_tracker/lazy_import_errors.py
- test/sample_libs/lazy_import_errors/__init__.py
- test/sample_libs/lazy_import_errors/foo.py
- test/test_main.py
This PR fixes a bug that can arise when a library uses `lazy_import_errors` and also attempts to perform top-level tracking. The bug shows up if the library in question uses standard `try/except` semantics for some of its optional dependencies.
As a side effect, tracking for libraries which use `lazy_import_errors` is much faster since it avoids the need to create a stack trace on each import.
> No lazy errors while tracking

- .pre-commit-config.yaml
- import_tracker/__main__.py
- import_tracker/import_tracker.py
- import_tracker/setup_tools.py
- test/sample_libs/side_effects/__init__.py
- test/sample_libs/side_effects/global_thing.py
- test/sample_libs/side_effects/mod.py
- test/test_lazy_import_errors.py
- test/test_main.py
- test/test_setup_tools.py
Though generally an anti-pattern, many libraries use [side effects](https://en.wikipedia.org/wiki/Side_effect_(computer_science)) at import time to handle global configuration tasks. I'm guilty of doing this often! This causes issues for `import_tracker` because downstream modules from the module with the global configuration often rely on the fact that the side-effect module is imported beforehand and that therefore the global configuration is in place. By default with `import_tracker`, these side-effect modules are configured as deferred imports and since the downstream libraries often don't explicitly import them, they never get imported and their side-effects never get triggered.
It would be nice to simply say that "we don't support this" but it would also severely limit the usability …
> Handle side effect libraries

- import_tracker/__main__.py
When a module is created using `imp.new_module` its `__spec__` attribute is created as `None`, so the `__spec__.name` call was raising. This fixes that line to use `mod.__name__` instead which should always be valid.
It's _really_ hard to exercise this case because the bug was only cropping up in the guts of `_DeferredModule.referenced_by`. I have verified that the library where this was done now gets past the broken point using this fix.
> Handle degenerate modules

- import_tracker/__main__.py
- import_tracker/import_tracker.py
- import_tracker/setup_tools.py
- test/test_import_tracker.py
- test/test_main.py
This PR adds a new `--submodules` arg to `main` (and a corresponding `submodules` arg to `track_modules`) that limits which submodules will be recursed on. It also uses the `extras_modules` arg to `parse_requirements` as `submodules` to avoid unnecessary work.
Closes #25
> Limited recursion 25

- import_tracker/__main__.py
- import_tracker/import_tracker.py
- test/test_main.py
This PR introduces a new argument to `main` and `track_module` that allows the output to contain stack trace information about where a given dependent import is coming from within the target library.
Closes #27 
* Move core logic of `ImportTrackerMetaFinder.find_spec` into a detail function `ImportTrackerMetaFinder._find_spec`
* Wrap `ImportTrackerMetaFinder._find_spec` in `ImportTrackerMetaFinder.find_spec` to optionally store a stack trace when an import is allowed through
* Plumb the arguments through `track_module`
* Full unit test coverate
* https://github.com/IBM/import-tracker/issues/31
> Track import stack 27

- README.md
- import_tracker/constants.py
- import_tracker/lazy_import_errors.py
- test/sample_libs/missing_dep/__init__.py
- test/sample_libs/missing_dep/mod.py
- test/sample_libs/missing_dep/other.py
- test/test_lazy_import_errors.py
Closes #29 
This PR introduces two new ways to customize the errors emitted when using `lazy_import_errors`:
1. The `get_extras_modules` argument takes a function which returns a `Set[str]` of the module names that are tracked as extras. If the `_LazyErrorAttr` triggers from within a stack that includes one of these extras modules, the error message is updated to include instructions on which extras set needs to be installed.
2. The `make_error_message` argument allows the user to specify a fully custom error message generation function
* Unit test coverage
* Validated with watson_nlp
> Custom import errors 29

- import_tracker/setup_tools.py
- test/sample_libs/single_extra/__init__.py
- test/sample_libs/single_extra/extra.py
- test/sample_libs/single_extra/not_extra.py
- test/test_setup_tools.py
This PR addresses #38. It is a partial solution that handles the case where there is a single extras module AND there are one-or-more non-extras modules. In the case where there's a single extras module and no other non-extras modules, the dependencies from the extras module will still be allocated to the global set because the dependency relationship with the parent has no alternate traversals of the import tree, so there is no separability between the child and the parent. This case should be _extremely_ rare, though, as using `import_tracker` in this case would be wildly overkill for such a toy example.
* If there is only a single `extras_module`, perform the full recursive tracking rather than limiting to just the single extras module
* If a single `extras_module` was given, filter …
> 🐛 Single extras 38

- .github/workflows/tests.yml
- Dockerfile
- import_tracker/__main__.py
- ppa.dockerfile
- requirements_test.txt
- scripts/fmt.sh
This PR addresses #40 by providing more robust heuristics for discovering the standard location of built-in libraries that are implemented as shared libraries.
* Add more robust heuristics for discovery `_std_dylib_dir`
* Add a base `ppa.dockerfile` that builds base images using PPA python (where the issue was observed)
* Extend the testing grid to include tests of all versions of python on PPA
* [UNRELATED BUG!] Actually build the unit test jobs against the target python versions!
* While adding the PPA tests, I realized that the PYTHON_VERSION was never passed as a `--build-arg` to the unit test builds. Fortunately, it was being done correctly for `release`
> C math builtin 40

- import_tracker/setup_tools.py
- test/test_setup_tools.py
Closes #41 
Fix the logic when a subset of submodules is held as extras
The new logic is to always track all submodules (this will be slower) so that all submodules that are not direct parents of extras modules can be merged into the set of common imports.
> SubsetOfSubmodules: 

- .isort.cfg
- import_tracker/__main__.py
- import_tracker/setup_tools.py
- test/sample_libs/direct_dep_ambiguous/__init__.py
- test/test_main.py
- test/test_setup_tools.py
Closes #48 
This PR uses the new `--detect_transitive` argument to differentiate between `direct` and `transitive` dependencies of modules within the target library that are not part of the extras and ensure that all `direct` dependencies of non-extras are held in the common `requirements`.
> 🐛 Direct deps in parse requirements 48

- import_tracker/__main__.py
- test/sample_libs/lazy_module/__init__.py
- test/sample_libs/lazy_module/lazy_deps.py
- test/sample_libs/lazy_module/mod.py
- test/test_main.py
Closes #50 
This PR fixes the accidental `getattr` call that was causing `LazyModule`s held as attributes of other modules to be imported when run through the `import_tracker` main entrypoint.
> 🐛 Lazy module trigger bug

- import_tracker/lazy_import_errors.py
- test/test_lazy_import_errors.py
- Fix case when `sys.meta_path` is modified (appended) by some other library. This issue was noticed when `sys.meta_path` was getting modified by `setuptools.command.build_py`. 
- Fix case when a library implementing lazy import errors (by using import-tracker) was getting used by another library implementing lazy import errors (nested lazy import error case)
> :bug: Fix nested lazy import and sys meta path modification issue

- import_tracker/lazy_import_errors.py
- test/test_lazy_import_errors.py
- Fix case where a class that uses a module from an optional dependency is used as base class for another module, where both classes are in lazy import error
- This fixes following error:
```
return super().__new__(
TypeError: __classcell__ must be a nonlocal cell, not <class 'NoneType'>
```
- `module_1.py`
```python
from sklearn import LinearSVM
class NewSVM(LinearSVM):
pass
```
- `module_2.py`
```python
from .module_2 import NewSVM
class Foo(NewSVM):
pass
```
- where these are included in `lazy_import_errors` because sklearn is an optional dependency
> :bug: Fix inheritance case for lazy imports

- import_tracker/lazy_import_errors.py
- test/sample_libs/decorator_deps/__init__.py
- test/sample_libs/decorator_deps/opt_decorator.py
- test/test_lazy_import_errors.py
- Fix the case where a function / decorator from optional dependency is being called at import time
> :bug: Fix import time optional deps call

- import_tracker/lazy_import_errors.py
- test/sample_libs/type_check_deps/type_check_dict.py
- test/sample_libs/type_check_deps/type_check_union.py
- test/test_lazy_import_errors.py
- Fixes the issues where an optional dependency class is used for type checking along with other types using a combining type, like Dict or Union.
based on #64 
1. `Dict[foo, str]`
2. `Union[foo, str]`
Typing is another one of the operations that happens at the import time. 
In both above scenarios, a hashing is performed under the hood in python that tries to make a unique combination of the presented types. Since we are replacing it with lazy module, without this fix, we are raising error for `__hash__` function, and thus the typing at import time, throws error.
> Add fix for typing

- import_tracker/lazy_import_errors.py
- test/test_lazy_import_errors.py
Not gonna lie I don't fully understand what's going on inside of `inspect.stack()` to make it so much slower than iterating through `sys._getframe()` but here we are.
This takes a partial import of a library that makes heavy use of `abc.ABC` from 650s back down to 4s.
> :zap: Remove inspect.stack() for performance

- .github/workflows/release.yml
- Dockerfile
- scripts/release.sh
- setup.py
This PR fixes some issues in the `3.2.0` release that failed to build the wheels for `3.11`/`3.12`
> Finish new version support
